model: transflower
dins: 375,64
douts: 375
input_modalities: "_pc,_mel"
output_modalities: _pc
input_lengths: 200,200
output_lengths: 200
output_time_offsets: 200
nlayers: 4
nhead: 8
scales: "[[16,0]]"
num_glow_coupling_blocks: 2
glow_use_attn: True
use_transformer_nn: True
use_pos_emb_coupling: True
#use_pos_emb_output: True
dhid: 512
cond_concat_dims: True
glow_norm_layer: batchnorm
glow_bn_momentum: 0.1
dropout: 0.6
#lr_policy: cosine
lr_policy: multistep
lr_decay_milestones: [50,100]
learning_rate: 7e-5
gradient_clip_val: 0.5
batch_size: 64
